//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteRegisteredLearningPlan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTTAIKHOAN
    {
        public string id { get; set; }
        public string hovaten { get; set; }
        public string sdt { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
