//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteRegisteredLearningPlan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUADANGKY
    {
        public string email { get; set; }
        public Nullable<int> mahp { get; set; }
        public Nullable<System.DateTime> ngaydk { get; set; }
        public int id { get; set; }
        public Nullable<int> active { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CTDT CTDT { get; set; }
    }
}
